In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

from sklearn.model_selection import train_test_split
sns.set()

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/2. ESPECIALIZACIÓN EN IA/CLASES UAO COLAB/Herramientas/PROYECTOS/Proyecto 3 regresión logistica/datasets/winequality-red.csv', 
                 sep=';')


In [ ]:
estado = []
for i in df['quality']: 
    if i >= 6:
        i = 1
        estado.append(i)
    else:
        i = 0
        estado.append(i)
df['estado'] = estado 
df.head(10)

fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  estado
0            7.4              0.70         0.00  ...      9.4        5       0
1            7.8              0.88         0.00  ...      9.8        5       0
2            7.8              0.76         0.04  ...      9.8        5       0
3           11.2              0.28         0.56  ...      9.8        6       1
4            7.4              0.70         0.00  ...      9.4        5       0
5            7.4              0.66         0.00  ...      9.4        5       0
6            7.9              0.60         0.06  ...      9.4        5       0
7            7.3              0.65         0.00  ...     10.0        7       1
8            7.8              0.58         0.02  ...      9.5        7       1
9            7.5              0.50         0.36  ...     10.5        5       0

[10 rows x 13 columns]

In [ ]:
df.isna().sum()


fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
estado                  0
dtype: int64

In [ ]:
df.describe().transpose()

count       mean  ...        75%        max
fixed acidity         1599.0   8.319637  ...   9.200000   15.90000
volatile acidity      1599.0   0.527821  ...   0.640000    1.58000
citric acid           1599.0   0.270976  ...   0.420000    1.00000
residual sugar        1599.0   2.538806  ...   2.600000   15.50000
chlorides             1599.0   0.087467  ...   0.090000    0.61100
free sulfur dioxide   1599.0  15.874922  ...  21.000000   72.00000
total sulfur dioxide  1599.0  46.467792  ...  62.000000  289.00000
density               1599.0   0.996747  ...   0.997835    1.00369
pH                    1599.0   3.311113  ...   3.400000    4.01000
sulphates             1599.0   0.658149  ...   0.730000    2.00000
alcohol               1599.0  10.422983  ...  11.100000   14.90000
quality               1599.0   5.636023  ...   6.000000    8.00000
estado                1599.0   0.534709  ...   1.000000    1.00000

[13 rows x 8 columns]

ver si meter outliersAQUI 

In [ ]:
seaborn.pairplot(df, hue = "estado")
plt.show()

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant

# the target column (in this case 'grade') should not be included in variables
#Categorical variables may or maynot be added if any


variables = df[['fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',]]
x = add_constant(variables)
vif = pd.DataFrame()
vif['VIF'] = [variance_inflation_factor(x.values,i) for i in range (x.shape[1])]
vif['features'] = x.columns
vif

VIF              features
0   1.710538e+06                 const
1   7.767512e+00         fixed acidity
2   1.789390e+00      volatile acidity
3   3.128022e+00           citric acid
4   1.702588e+00        residual sugar
5   1.481932e+00             chlorides
6   1.963019e+00   free sulfur dioxide
7   2.186813e+00  total sulfur dioxide
8   6.343760e+00               density
9   3.329732e+00                    pH
10  1.429434e+00             sulphates
11  3.031160e+00               alcohol

In [ ]:
x = df.drop('estado', axis =1 )
y = df['estado']

In [ ]:
scaler = MinMaxScaler()
scaler.fit(x)
scaled_x = scaler.transform(x)

REGRESIÓN LOGISTICA

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(scaled_x, y , test_size = 0.3)

In [ ]:
reg = LogisticRegression() 
reg.fit(x_train,y_train) 

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_hat = reg.predict(x_test) # y_hat holding the prediction made with the algorithm using x_test

In [ ]:
acc = metrics.accuracy_score(y_hat,y_test)# To know the accuracy
acc

1.0

In [ ]:
reg.intercept_ # Intercept of the regression

array([-7.72893805])

In [ ]:
reg.coef_ # coefficients of the variables / features 

array([[ 0.1617105 , -1.53598592, -0.13196723,  0.17834669, -0.30937825,
         0.22890698, -1.28165436, -0.37183744,  0.34562887,  1.2646259 ,
         2.17758426, 15.03089346]])

In [ ]:
result = pd.DataFrame(data = x.columns, columns = ['Features'])
result['weight'] = np.transpose(reg.coef_)
result['odds'] = np.exp(np.transpose(reg.coef_))
result

Features     weight          odds
0          fixed acidity   0.161711  1.175520e+00
1       volatile acidity  -1.535986  2.152434e-01
2            citric acid  -0.131967  8.763697e-01
3         residual sugar   0.178347  1.195240e+00
4              chlorides  -0.309378  7.339031e-01
5    free sulfur dioxide   0.228907  1.257225e+00
6   total sulfur dioxide  -1.281654  2.775777e-01
7                density  -0.371837  6.894663e-01
8                     pH   0.345629  1.412878e+00
9              sulphates   1.264626  3.541768e+00
10               alcohol   2.177584  8.824962e+00
11               quality  15.030893  3.371585e+06

In [ ]:
cm = confusion_matrix(y_hat,y_test)
cm

array([[246,   0],
       [  0, 234]])

In [ ]:
# Format for easier understanding
cm_df = pd.DataFrame(cm)
cm_df.columns = ['Predicted 0','Predicted 1']
cm_df = cm_df.rename(index={0: 'Actual 0',1:'Actual 1'})
cm_df

Predicted 0  Predicted 1
Actual 0          246            0
Actual 1            0          234

In [ ]:
all_predict = reg.predict(x_test)
print(all_predict)

print("Datos de Validacion\n", y_test)


[1 0 0 1 1 0 0 0 1 0 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 0
 0 1 1 0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0 1 0 1 1 1 1 0 1 0 1 0 0 0 1 0 1 0
 0 0 1 0 0 1 0 1 1 0 1 1 1 1 0 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 1 0 0 0
 0 1 0 0 1 0 1 1 0 1 0 1 0 1 0 1 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 1 1 1 0 1
 0 1 1 1 1 0 1 0 1 0 1 1 1 0 1 1 1 0 0 1 0 0 0 1 0 0 0 1 0 1 0 1 1 0 0 1 0
 0 0 0 1 1 1 1 0 0 1 1 1 0 1 0 0 1 0 1 1 1 0 0 1 0 1 1 1 1 0 0 1 1 1 0 1 1
 0 0 0 1 1 0 0 0 0 1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 1 0 1 0 0 0 1 1 1 1 1 1 0
 0 0 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 1 0 1 1 1 0 1 1 0 1 0 1 1 0 0 0 0 1 0 0
 1 1 1 0 0 1 1 0 1 0 1 0 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 0 0 1 0 0 0 0 1 0 0
 0 1 1 0 1 0 0 0 0 1 1 0 0 1 0 1 1 1 1 1 1 1 0 0 1 0 1 0 0 1 1 0 1 0 0 1 0
 0 0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 1 0 1 0 0 0 1 1 0 0 1 0 1 1 1 1 0 0 0 1 1
 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 1 0 1 0 1 1 1 0 1 1 0 1 0 0
 1 0 1 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 1 0 0 1 1 0 1 0 0 1 1 1 0 0 1 1 1 1]
Datos de Validacion
 366  

hacer pruebas con más datos


cambiar el estado > 6.5